### ISSUE TITLE
ovs-vsctl add port failed

### ISSUE THREAD

**Issue by mJace** [socketplane/docker-ovs#10]
I'm using docker to create a network topology by containers.
and I created a few container by "docker-ovs"
also, followed the official tutorial "Building a point-to-point connection"
https://docs.docker.com/articles/networking/#building-a-point-to-point-connection
connected my containers,
however, after I type ovs-vsctl add-port br0 A
there will be a error, says

root@jace# docker exec node1 ovs-vsctl add-port br0 A
ovs-vsctl: Error detected while setting up 'A'.  See ovs-vswitchd log for details.

do you have any clue or any information about this problem?

**Comment by dave-tucker** [comment]
If you are planning on running OVS in userspace mode, you will need to set the Bridge's `datapath_type=netdev`. If not, please ensure the OVS Kernel Module is loaded in you host e.g `modprobe openvswitch`

**Comment by mJace** [comment]
I've checked my kernel module by lsmod | grep openvswitch
and it was loaded in for sure, also I add datapath_type=netdev when creating bridge
that's why I feel kinda strange.

**Comment by dave-tucker** [comment]
ok, you don't need to use `datapath_type=netdev` when the kernel module is loaded.
if you can create a new bridge and try adding a port, that would be great....
you can also use `docker logs <container_id>` to get some output for OVS as to why this might have failed

**Comment by mJace** [comment]
Thanks for your help, it seem like I loaded openvswitch.ko and use datapath_type=netdev at the same time.

**Comment by mehwishZaidi** [comment]
hey can you please let me kn ow how you resolve this issue

**Comment by mJace** [comment]
Hi mehwishZaidi,  the conversation above contains the solution to this problem.
Are you still unable to solve your problem?
