### ISSUE TITLE
trouble bringing up Vagrant box from scratch

### ISSUE THREAD

**Issue by flavio-fernandes** [socketplane/docker-ovs#5]
I tried bringing up the vagrant box from scratch [1] and hit an issue with docker:

	[root@centos ~]# docker -d 2014/12/04 17:11:43 docker daemon: 1.3.1 c78088f/1.3.1; execdriver: native; graphdriver: [10307ed2] +job 	
	serveapi(unix:///var/run/docker.sock) docker: relocation error: docker: symbol dm_task_get_info_with_deferred_remove, version Base not defined in file 
	libdevmapper.so.1.02 with link time reference

I looked around an wonder if the issue is related to 32 bit not being supported [2] [3]? Any chance you know how to fix this? Do you also see this in your setup?

[1] https://gist.github.com/e3626f90bf8fa82f7eda
[2] https://groups.google.com/forum/#!topic/docker-user/QA48ecqZKww
[3] http://mwhiteley.com/linux-containers/2013/08/31/docker-on-i386.html

**Comment by dave-tucker** [comment]
Closing as we've dropped Packer in favour of Dockerfiles
https://github.com/socketplane/docker-ovs/commit/f22db0e44235fa77f85857c69a1626ae22f9c610
