### ISSUE TITLE
sudo docker pull davetucker/docker-ovs --> Tag latest not found in repository davetucker/docker-ovs

### ISSUE THREAD

**Issue by flavio-fernandes** [socketplane/docker-ovs#6]
[vagrant@centos ~]$ sudo docker pull davetucker/docker-ovs
Pulling repository davetucker/docker-ovs
2014/12/04 17:37:25 Tag latest not found in repository davetucker/docker-ovs
[vagrant@centos ~]$ sudo docker pull davetucker/docker-ovs:2.1.2
Pulling repository davetucker/docker-ovs
9ae424c5d3b7: Download complete
Status: Downloaded newer image for davetucker/docker-ovs:2.1.2
[vagrant@centos ~]$ sudo docker pull davetucker/docker-ovs:2.3.0
Pulling repository davetucker/docker-ovs
00a298722d96: Download complete
Status: Downloaded newer image for davetucker/docker-ovs:2.3.0
[vagrant@centos ~]$ sudo docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
davetucker/docker-ovs   2.3.0               00a298722d96        11 weeks ago        31.14 MB
davetucker/docker-ovs   2.1.2               9ae424c5d3b7        11 weeks ago        27.53 MB
[vagrant@centos ~]$

**Comment by dave-tucker** [comment]
Fixed in https://github.com/socketplane/docker-ovs/commit/f22db0e44235fa77f85857c69a1626ae22f9c610

Note: The new repo is `socketplane/openvswitch`
